name: Build and deploy the Learning.CICD service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: 1.0.1

jobs:
  build_then_push_to_registry:
    name: Build Image and deploy for Learning CICD
    timeout-minutes: 15
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
          
      - name: Build the Learning CICD Docker image
        run: |
          docker build -t damtuandatdev96/datdt44:latest -f ./CICD/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push Learning CICD Docker Image to docker registry
        run: docker push damtuandatdev96/datdt44:latest

      - name: Clean up docker builder cache
        run: docker builder prune -f
  
  deploy_hosted_machine:
    name: Deploy Learning.CICD service
    timeout-minutes: 15
    needs: [ build_then_push_to_registry ]
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Pull Learning.CICD image 
        run: |
          docker pull damtuandatdev96/datdt44:latest
          docker-compose -f ./CICD/docker-compose.yml up -d
          docker image prune -f
